version: '2'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3305:3306"
    volumes:
      - "./volumes/mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: memo
      MYSQL_USER: memo
      MYSQL_PASSWORD: memo
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command:
      - '--character-set-server=utf8'
      - '--collation-server=utf8_unicode_ci'
    container_name: memo_mysql

  mysql_testing:
    image: mysql:5.7
    ports:
      - "3304:3306"
    volumes:
      - "./volumes/mysql_testing:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: memo_testing
      MYSQL_USER: memo_testing
      MYSQL_PASSWORD: memo_testing
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command:
      - '--character-set-server=utf8'
      - '--collation-server=utf8_unicode_ci'
    container_name: memo_mysql_testing

  php-fpm:
    build: ./docker/php-local
    links:
      - mysql
      - mysql_testing
      - redis
    volumes:
      - "./app:/app"
    extends:
      file: docker/env-local.yml
      service: base
    container_name: memo_php

  #  cron:
  #    build: ./docker/php-local
  #    command: /app/cron.sh
  #    links:
  #      - mysql
  #    volumes:
  #      - "./app:/app"
  #    extends:
  #      file: docker/env-local.yml
  #      service: base

  laravel-worker:
    build: ./docker/php-local
    links:
      - mysql
      - mysql_testing
      - redis
    volumes:
      - "./app:/app"
    logging:
      driver: none
    environment:
      APP_LOG_LEVEL: critical
    extends:
      file: docker/env-local.yml
      service: base
    command: "php /app/artisan queue:work --daemon --queue=import,default --tries=10"
    container_name: memo_worker

  nginx:
    image: nginx:1.9.10
    volumes:
      - "./app:/app"
      - "./docker/nginx-dev/vhost.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/nginx-dev/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - php-fpm
    ports:
      - "8022:80"
    container_name: memo_nginx

  redis:
    image: redis:latest
    container_name: memo_redis
