version: "2"
services:
  jenkins_mysql:
    image: mysql:5.7
    ports:
      - "3301:3306"
    volumes:
      - "../volumes/mysql:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: memo
      MYSQL_USER: memo
      MYSQL_PASSWORD: memo
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command:
      - '--character-set-server=utf8'
      - '--collation-server=utf8_unicode_ci'
    container_name: jenkins_memo_mysql

  jenkins_mysql_testing:
    image: mysql:5.7
    ports:
      - "3300:3306"
    volumes:
      - "../volumes/mysql_testing:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: memo_testing
      MYSQL_USER: memo_testing
      MYSQL_PASSWORD: memo_testing
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command:
      - '--character-set-server=utf8'
      - '--collation-server=utf8_unicode_ci'
    container_name: jenkins_memo_mysql_testing

  jenkins_php-fpm:
    build: ../docker/php-local
    links:
      - jenkins_mysql
      - jenkins_mysql_testing
      - jenkins_redis
    volumes:
      - "../app:/app"
      #- "../php/ini:/usr/local/etc/php"
    extends:
      file: ../docker/env-local.yml
      service: base
    container_name: jenkins_memo_php
    environment:
      UNIQUE_LEVEL: 10
      APP_DEBUG: 1
      APP_ENV: "testing"
      DEBUGBAR_ENABLED: 1
      WORK_COLLECTION_LIMIT: 5

  #  cron:
  #    build: ./docker/php-local
  #    command: /app/cron.sh
  #    links:
  #      - mysql
  #    volumes:
  #      - "./app:/app"
  #    extends:
  #      file: docker/env-local.yml
  #      service: base

  jenkins_laravel-worker:
    build: ../docker/php-local
    links:
      - jenkins_mysql
      - jenkins_mysql_testing
      - jenkins_redis
    volumes:
      - "../app:/app"
    logging:
      driver: none
    environment:
      APP_LOG_LEVEL: critical
    extends:
      file: ../docker/env-local.yml
      service: base
    command: "php /app/artisan queue:work --daemon --queue=import,default --tries=10"
    container_name: jenkins_memo_worker

  jenkins_nginx:
    image: nginx:1.9.10
    volumes:
      - "../app:/app"
      - "../docker/nginx-dev/vhost.conf:/etc/nginx/conf.d/default.conf"
      - "../docker/nginx-dev/nginx.conf:/etc/nginx/nginx.conf"
    links:
      - jenkins_php-fpm
    ports:
      - "8029:80"
    container_name: jenkins_memo_nginx

  jenkins_redis:
    image: redis:latest
    container_name: jenkins_memo_redis